### ISSUE TITLE
OpenSSL::Cipher::Cipher is deprecated

### ISSUE THREAD

**Issue by mitchmeyer1** [chicks/aes#15]
gems/aes-0.5.0/lib/aes/aes.rb:151: warning: constant OpenSSL::Cipher::Cipher is deprecated.

On the newest version.  Is any of the owners still monitoring this?  I can try to patch it up and make a pull request if anyones out there

**Comment by dotanlang** [comment]
I'm having this problem too after upgrading to Ruby 2.5.3
Any news here?

**Comment by colto** [comment]
This is already fixed on master, it would just be nice if a new tag would be created (0.5.1 ?)

**Comment by colto** [comment]
@chicks @ashcmd @nikolasgd @Malet a gentle bump for a new gem version to fix this deprecation.

**Comment by varac** [comment]
@chicks Please release a new version, thanks !

**Comment by Kur0x** [comment]
@chicks Please release a new version, thanks !

**Comment by vanaltj** [comment]
Sorry folks, I'd gotten maintainership intending to take care of this last year but got busy and it fell through the cracks. Today, 0.5.1 is released and resolves this deprecation warning.
