### ISSUE TITLE
constant OpenSSL::Cipher::Cipher is deprecated

### ISSUE THREAD

**Issue by snood1205** [chicks/aes#8]
`OpenSSL::Cipher::Cipher` has been deprecated in favor of `OpenSSL::Cipher` per [this doc](https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/Cipher/Cipher.html).

**Comment by jalerson** [comment]
I just fixed it in my fork: [https://github.com/jalerson/aes](https://github.com/jalerson/aes)

You just need to refer to my repository in your Gemfile:

`gem 'aes', git: 'https://github.com/jalerson/aes'`

**Comment by Ch4s3** [comment]
Just as a heads up, this may break you implementation if you used a key or iv longer than 16 bytes https://github.com/ruby/ruby/commit/ce635262f53b760284d56bb1027baebaaec175d1

**Comment by dotanlang** [comment]
Is this the solution?
Is there any official fix?
I'm having this problem after upgrading ruby to 2.5.3

**Comment by jcabasc** [comment]
@dotanlang actually that repo no longer exists.

**Comment by matthias-g** [comment]
The problem is fixed on the master branch: `gem 'aes', git: 'https://github.com/chicks/aes'`

**Comment by vanaltj** [comment]
Sorry folks, I'd gotten maintainership last year intending to take care of this but then let it fall through the cracks. Now, 0.5.1 is finally released resolving this deprecation warning.
